version: '3'
services:
  api:
    image: phantoscope/api-server:v0.1.0
    ports:
      - "5000:5000"
    environment:
      - MINIO_ADDR=${LOCAL_ADDRESS}:9000
      - UPLOAD_FOLDER=/tmp
      - MILVUS_ADDR=milvus
      - SEARCH_IMAGES_DATABASE_EP=mysql://root:passwd@mysql:3306/search
      - SEARCH_IMAGES_DATABASE_USERNAME=root
      - SEARCH_IMAGES_DATABASE_PASSWD=passwd
      - MILVUS_PORT=19530
      - MINIO_BUCKET_NUM=20
    depends_on:
      - milvus
      - minio
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
    ports:
      - "3306:3306"
    volumes:
      - /mnt/om/mysql:/var/lib/mysql
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passwd
    ports:
      - "27017:27017"
    volumes:
      - /mnt/om/mongo:/data/db
  milvus:
    image: milvusdb/milvus:0.10.0-cpu-d061620-5f3c00
    ports:
      - "19530:19530"
      - "8080:8080"
    volumes:
      - /mnt/om/milvus/db:/var/lib/milvus/db
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - /mnt/om/minio/data:/data
    command: ["server","/data"]
  vgg:
    image: psoperator/vgg16:latest
    ports:
      - "50001:50001"
    environment:
      - OP_ENDPOINT=${LOCAL_ADDRESS}:50001
    depends_on:
      - api
