version: '3'
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
    ports:
      - "3306:3306"
  milvus:
    image: milvusdb/milvus:0.10.0-cpu-d061620-5f3c00
    ports:
      - "19530:19530"
      - "8080:8080"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    command: ["server","/data"]
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passwd
    ports:
      - "27017:27017"
